lr: 0.0001
seed: 2
if_cuda: True
gamma: 0.5
log_dir: 'logs'
train_batch: 8
val_batch: 8
test_batch: 8
num_workers: 8
model_name: 'denoise-decoder-64'
data_filepath: '/home/kevin/data'
dataset: 'elastic_pendulum'
num_frames: 60
lr_schedule: [20, 50, 100, 300, 600]
num_gpus: 1
epochs: 1000